### ISSUE TITLE
Change the food consumption system.

### ISSUE THREAD

**Issue by FitchKrause** [MovTery/DestructionDifficulty#1]
I think the best option would be to subtract not the hunger level, but the saturation level for each broken block.  This sounds much more honest than a random chance of losing a certain level of hunger. For example, in the settings, do this:
"exhaust amount per breaking a block ":0.025(the value can be edited).

**Comment by MovTery** [comment]
> I think the best option would be to subtract not the hunger level, but the saturation level for each broken block. This sounds much more honest than a random chance of losing a certain level of hunger. For example, in the settings, do this: "exhaust amount per breaking a block ":0.025(the value can be edited).

Thank you for your suggestion. I gave it a try following your method, and indeed, it seems like a good idea. However, I am currently contemplating how to integrate it more effectively with the Mod's existing solution. Perhaps we can consider adding both of these different approaches into the Mod, providing users with more choices and flexibility.
